import { ymFromDate } from '../lib/date';
import { eurosToCents } from '../lib/money';
import { uid } from '../lib/id';
import type { Account, AppState, Budget, Charge } from './types';

export function seedState(now = new Date()): AppState {
  const nowIso = now.toISOString();
  const accounts: Account[] = [
    { id: 'BS_PERSO', name: 'BS_PERSO', kind: 'perso', active: true },
    { id: 'CA_PERSO', name: 'CA_PERSO', kind: 'perso', active: true },
    { id: 'LCL_PERSO', name: 'LCL_PERSO', kind: 'perso', active: true },
    { id: 'CC_CA', name: 'CC_CA', kind: 'commun', active: true },
    { id: 'CC_LCL', name: 'CC_LCL', kind: 'commun', active: true },
    { id: 'BS_HIDAYA', name: 'BS_HIDAYA', kind: 'perso', active: true },
    { id: 'BS_IMANI', name: 'BS_IMANI', kind: 'perso', active: true },
  ];

  const charges: Charge[] = [
    {
      id: uid('chg'),
      name: 'Prêt maison',
      amountCents: eurosToCents(1347.3),
      sortOrder: 10,
      dayOfMonth: 5,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Pinel',
      amountCents: eurosToCents(312.6),
      sortOrder: 20,
      dayOfMonth: 3,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'EDF',
      amountCents: eurosToCents(352),
      sortOrder: 30,
      dayOfMonth: 5,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Eau (Noreade)',
      amountCents: eurosToCents(66),
      sortOrder: 40,
      dayOfMonth: 8,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Spotify',
      amountCents: eurosToCents(15.17),
      sortOrder: 50,
      dayOfMonth: 9,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Netflix',
      amountCents: eurosToCents(3.98),
      sortOrder: 60,
      dayOfMonth: 12,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Alarme',
      amountCents: eurosToCents(21.5),
      sortOrder: 70,
      dayOfMonth: 14,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Assurances MAAF',
      amountCents: eurosToCents(267.08),
      sortOrder: 80,
      dayOfMonth: 16,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Assurance décès',
      amountCents: eurosToCents(7.65),
      sortOrder: 85,
      dayOfMonth: 16,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Assurance prêt maison (Kereis)',
      amountCents: eurosToCents(27.98),
      sortOrder: 90,
      dayOfMonth: 18,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Assurance prêt maison (Multi Impact)',
      amountCents: eurosToCents(82.92),
      sortOrder: 100,
      dayOfMonth: 18,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Frais bancaires (compte commun)',
      amountCents: eurosToCents(3.9),
      sortOrder: 110,
      dayOfMonth: 20,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Taxe foncière',
      amountCents: eurosToCents(152),
      sortOrder: 120,
      dayOfMonth: 25,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'manuel',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Impôts - acomptes fonciers',
      amountCents: eurosToCents(65),
      sortOrder: 125,
      dayOfMonth: 25,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'manuel',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Crèche',
      amountCents: eurosToCents(50),
      sortOrder: 128,
      dayOfMonth: 20,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'manuel',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Courses',
      amountCents: eurosToCents(600),
      sortOrder: 130,
      dayOfMonth: 28,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'manuel',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Cantine',
      amountCents: eurosToCents(48),
      sortOrder: 132,
      dayOfMonth: 20,
      accountId: 'CC_CA',
      scope: 'commun',
      splitPercent: 50,
      payment: 'manuel',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Assurance Pinel (LCL)',
      amountCents: eurosToCents(46.12),
      sortOrder: 140,
      dayOfMonth: 28,
      accountId: 'CC_LCL',
      scope: 'commun',
      splitPercent: 50,
      payment: 'auto',
      active: true,
      destination: { kind: 'text', text: 'Assurance Pinel' },
    },
    {
      id: uid('chg'),
      name: 'Virement épargne (BS Hidaya)',
      amountCents: eurosToCents(10),
      sortOrder: 10,
      dayOfMonth: 1,
      accountId: 'BS_PERSO',
      scope: 'perso',
      payment: 'auto',
      destination: { kind: 'account', accountId: 'BS_HIDAYA' },
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Virement épargne (BS Imani)',
      amountCents: eurosToCents(10),
      sortOrder: 20,
      dayOfMonth: 1,
      accountId: 'BS_PERSO',
      scope: 'perso',
      payment: 'auto',
      destination: { kind: 'account', accountId: 'BS_IMANI' },
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Groupe',
      amountCents: eurosToCents(25),
      sortOrder: 25,
      dayOfMonth: 1,
      accountId: 'CA_PERSO',
      scope: 'perso',
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Frais CA (perso)',
      amountCents: eurosToCents(7.1),
      sortOrder: 27,
      dayOfMonth: 5,
      accountId: 'CA_PERSO',
      scope: 'perso',
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Mutuelle',
      amountCents: eurosToCents(85),
      sortOrder: 30,
      dayOfMonth: 7,
      accountId: 'CA_PERSO',
      scope: 'perso',
      payment: 'auto',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Prêt familial (remboursement)',
      amountCents: eurosToCents(300),
      sortOrder: 40,
      dayOfMonth: 10,
      accountId: 'CA_PERSO',
      scope: 'perso',
      payment: 'manuel',
      active: true,
    },
    {
      id: uid('chg'),
      name: 'Téléphone',
      amountCents: eurosToCents(25),
      sortOrder: 50,
      dayOfMonth: 20,
      accountId: 'BS_PERSO',
      scope: 'perso',
      payment: 'auto',
      active: true,
    },
  ];

  const budgets: Budget[] = [
    {
      id: uid('bud'),
      name: 'Budget perso',
      amountCents: eurosToCents(150),
      accountId: 'BS_PERSO',
      active: true,
    },
    {
      id: uid('bud'),
      name: 'Essence',
      amountCents: eurosToCents(150),
      accountId: 'CA_PERSO',
      active: true,
    },
  ];

  const ym = ymFromDate(now);

  return {
    version: 1,
    modifiedAt: nowIso,
    salaryCents: eurosToCents(3968.79),
    accounts,
    charges,
    budgets,
    months: {
      [ym]: {
        ym,
        archived: false,
        createdAt: nowIso,
        updatedAt: nowIso,
        charges: {},
        budgets: {
          [budgets[0]!.id]: {
            expenses: [
              {
                id: uid('exp'),
                date: `${ym}-03`,
                label: 'Barbier',
                amountCents: eurosToCents(50),
              },
              {
                id: uid('exp'),
                date: `${ym}-04`,
                label: 'Carrefour',
                amountCents: eurosToCents(6.79),
              },
              {
                id: uid('exp'),
                date: `${ym}-05`,
                label: 'Pharmacie',
                amountCents: eurosToCents(5.4),
              },
              {
                id: uid('exp'),
                date: `${ym}-06`,
                label: 'Carrefour',
                amountCents: eurosToCents(3.92),
              },
              {
                id: uid('exp'),
                date: `${ym}-07`,
                label: 'Amazon',
                amountCents: eurosToCents(35.71),
              },
              {
                id: uid('exp'),
                date: `${ym}-08`,
                label: 'Restau',
                amountCents: eurosToCents(26.8),
              },
              {
                id: uid('exp'),
                date: `${ym}-09`,
                label: "McDonald's",
                amountCents: eurosToCents(6.75),
              },
            ],
          },
          [budgets[1]!.id]: {
            expenses: [
              {
                id: uid('exp'),
                date: `${ym}-05`,
                label: 'Plein',
                amountCents: eurosToCents(60),
              },
            ],
          },
        },
      },
    },
  };
}
